export type SupportEvent = {
  id: string;
  event_type?: string;
  actor_name?: string;
  actor_role?: string;
  visibility?: string;
  body?: string;
  previous_value?: string;
  new_value?: string;
  created_at?: string;
};

export type SupportTicketRow = Record<string, unknown> & {
  id: string;
  ticket_number?: string;
  subject?: string;
  status?: string;
  status_label?: string;
  priority?: string;
  priority_label?: string;
  category?: string;
  category_label?: string;
  description?: string;
  created_at?: string;
  updated_at?: string;
  last_activity_at?: string;
  reporter_type?: string;
  reporter_name?: string;
  reporter_public_id?: string;
  reporter_phone?: string;
  reporter_email?: string;
  reporter_language?: string;
  guest_name?: string;
  guest_phone?: string;
  guest_email?: string;
  user_id?: string;
  related_booking_id?: string;
  booking?: Record<string, unknown>;
  booking_number?: string;
  service_name?: string;
  booking_date?: string;
  start_time?: string;
  booking_location?: string;
  booking_customer_name?: string;
  booking_pujari_name?: string;
  contact_source?: string;
  sla_due_at?: string;
  sla_hours?: number | string;
  assigned_admin_id?: string;
  assigned_at?: string;
  expected_resolution?: string;
  additional_info?: string;
  events?: SupportEvent[];
  resolution?: string;
  resolution_type?: string;
  resolution_type_label?: string;
  resolved_at?: string;
  resolution_outcome?: string;
  escalated_to?: string;
  escalated_to_label?: string;
  escalated_at?: string;
  escalation_reason?: string;
};

export type DirectoryPerson = {
  id: string;
  name?: string;
  phone?: string;
  email?: string;
  public_id?: string;
};
