import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import fs from "fs";
import path from "path";
import { defineConfig, loadEnv, type Plugin } from "vite";

function firebaseMessagingSwPlugin(envDir: string, publicDir: string): Plugin {
  const writeSw = (mode: string) => {
    const fileEnv = loadEnv(mode, envDir, "VITE_FIREBASE_");
    const env = {
      ...fileEnv,
      ...Object.fromEntries(
        Object.entries(process.env).filter(
          ([key, value]) => key.startsWith("VITE_FIREBASE_") && Boolean(value)
        )
      ),
    } as Record<string, string>;
    const config = {
      apiKey: env.VITE_FIREBASE_API_KEY || "",
      authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || "",
      projectId: env.VITE_FIREBASE_PROJECT_ID || "",
      storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || "",
      messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
      appId: env.VITE_FIREBASE_APP_ID || "",
    };
    const body = `/* Generated by Vite from VITE_FIREBASE_* — never put Admin SDK JSON here. */
importScripts("https://www.gstatic.com/firebasejs/12.19.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/12.19.0/firebase-messaging-compat.js");

const firebaseConfig = ${JSON.stringify(config, null, 2)};

if (firebaseConfig.apiKey && firebaseConfig.projectId && firebaseConfig.appId) {
  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();
  messaging.onBackgroundMessage((payload) => {
    const title =
      (payload.notification && payload.notification.title) ||
      (payload.data && payload.data.title) ||
      "BSeva";
    const bodyText =
      (payload.notification && payload.notification.body) ||
      (payload.data && payload.data.body) ||
      "";
    const link = (payload.data && payload.data.link) || "/";
    if (payload.notification) return;
    return self.registration.showNotification(title, {
      body: bodyText,
      icon: "/bseva-logo.png",
      data: { link },
    });
  });
}

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const data = event.notification.data || {};
  const nested = data.FCM_MSG && data.FCM_MSG.data ? data.FCM_MSG.data : {};
  const link = data.link || nested.link || "/";
  event.waitUntil(
    (async () => {
      const all = await clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of all) {
        if ("focus" in client) {
          await client.focus();
          client.postMessage({ type: "BSEVA_NOTIFICATION_CLICK", link });
          return;
        }
      }
      const url = new URL(link, self.location.origin).href;
      await clients.openWindow(url);
    })()
  );
});
`;
    fs.mkdirSync(publicDir, { recursive: true });
    fs.writeFileSync(path.join(publicDir, "firebase-messaging-sw.js"), body);
  };

  return {
    name: "firebase-messaging-sw",
    config(_cfg, { mode }) {
      writeSw(mode);
    },
  };
}

const repoRoot = path.resolve(import.meta.dirname, "..");
const publicDir = path.resolve(import.meta.dirname, "client", "public");
const plugins = [react(), tailwindcss(), firebaseMessagingSwPlugin(repoRoot, publicDir)];

export default defineConfig({
  plugins,
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "client", "src"),
      "@shared": path.resolve(import.meta.dirname, "shared"),
      "@assets": path.resolve(import.meta.dirname, "attached_assets"),
      "@bseva/locales": path.resolve(repoRoot, "packages/locales/src/index.ts"),
      "@bseva/config": path.resolve(repoRoot, "packages/config/src/index.ts"),
      "@bseva/types": path.resolve(repoRoot, "packages/types/src/index.ts"),
    },
  },
  // Load from repo root `.env` (and local overrides in this package)
  envDir: path.resolve(import.meta.dirname, ".."),
  root: path.resolve(import.meta.dirname, "client"),
  publicDir: path.resolve(import.meta.dirname, "client", "public"),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    host: true,
    allowedHosts: [
      ".manuspre.computer",
      ".manus.computer",
      ".manus-asia.computer",
      ".manuscomputer.ai",
      ".manusvm.computer",
      "localhost",
      "127.0.0.1",
    ],
    fs: {
      strict: true,
      allow: [repoRoot],
      deny: ["**/.*"],
    },
  },
});
