/** Same country list as the working web BookingWizard virtual step. */
export const VIRTUAL_COUNTRIES = [
  { id: "IN", label: "India" },
  { id: "AE", label: "United Arab Emirates" },
  { id: "US", label: "United States" },
  { id: "GB", label: "United Kingdom" },
  { id: "SG", label: "Singapore" },
  { id: "MY", label: "Malaysia" },
  { id: "AU", label: "Australia" },
  { id: "CA", label: "Canada" },
  { id: "NZ", label: "New Zealand" },
  { id: "DE", label: "Germany" },
  { id: "FR", label: "France" },
  { id: "NL", label: "Netherlands" },
  { id: "IE", label: "Ireland" },
  { id: "JP", label: "Japan" },
  { id: "TH", label: "Thailand" },
  { id: "SA", label: "Saudi Arabia" },
  { id: "QA", label: "Qatar" },
  { id: "KW", label: "Kuwait" },
  { id: "OM", label: "Oman" },
  { id: "BH", label: "Bahrain" },
  { id: "ZA", label: "South Africa" },
] as const;
